# All relative paths and API endpoints
paths:
  assets:
    fonts:
      main: "assets/fonts/Figtree-Light.ttf"
    images:
      appLogo: "assets/icons/appLogo.png"
      uninstall: "assets/icons/uninstall.png"
      uninstalling: "assets/icons/uninstalling.png"
      uninstalled: "assets/icons/uninstalled.png"
      failed: "assets/icons/failed.png"
      install: "assets/icons/install.png"
      installing: "assets/icons/installing.png"
      installed: "assets/icons/installed.png"
      arrowDown: "assets/icons/fold.png"
  executables:
    library:
      darwin: "./go_app"
      win32: "./go_app.exe"
      win64: "./go_app.exe"
      linux: "./go_app"
  search:
    darwin:
      - "/Library/Frameworks/Python.framework/Versions"
      - "/usr/local/bin"
      - "/usr/bin"
      - "/opt/homebrew/bin"
    win32: "Needs to be implemented"
    win64: "Needs to be implemented"
    linux: "Needs to be implemented"

api:
  pypi:
    libraryDetails: "https://pypi.org/pypi/{}/json"
    packageList: "https://pypi.org/simple/"
