# All relative paths and API endpoints
paths:
  assets:
    fonts:
      main: "assets/fonts/Figtree-Light.ttf"
    images:
      appLogo: "assets/icons/appLogo.png"
      uninstall: "assets/icons/uninstall.png"
      uninstalling: "assets/icons/uninstalling.png"
      uninstalled: "assets/icons/uninstalled.png"
      failed: "assets/icons/failed.png"
      install: "assets/icons/install.png"
      installing: "assets/icons/installing.png"
      installed: "assets/icons/installed.png"
      arrowDown: "assets/icons/fold.png"
      add: "assets/icons/add.svg"
      close: "assets/icons/close.svg"
      minimize: "assets/icons/minimize.svg"
      maximize: "assets/icons/maximize.svg"
      settings: "assets/icons/settings.png"
      reset: "assets/icons/reset.png"
  executables:
    load_library:
      darwin: "./bin/darwin/library-loader"
      win32: "./bin/win32/library-loader.exe" # change this to the correct path
    pypiDetailFetcher:
      darwin: "./bin/darwin/pypi-fetcher"
      win32: "./bin/win32/pypi-fetcher.exe" # change this to the correct path
    find_local_environment:
      darwin: "./bin/darwin/env-finder"
      win32: "./bin/win32/env-finder.exe" # change this to the correct path

  search:
    darwin:
      - "/Library/Frameworks/Python.framework/Versions"
      - "/usr/local/bin"
      - "/usr/bin"
      - "/opt/homebrew/bin"
    win32: "Needs to be implemented"
    win64: "Needs to be implemented"
    linux: "Needs to be implemented"

api:
  pypi:
    libraryDetails: "https://pypi.org/pypi/{}/json"
    packageList: "https://pypi.org/simple/"
